# -*- coding: utf-8 -*-
"""SCT_DA_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16rlDjSrJek6gAMARBm95XIFg79rUwHLI
"""

import pandas as pd

# Load the dataset into a DataFrame
df = pd.read_csv('Superstore sales dataset.csv')

# Display the first 5 rows to make sure it loaded correctly
df.head()

# 1. Check for missing values in each column
print("--- Missing Values Count ---")
print(df.isnull().sum())
print("\n" + "="*40 + "\n")

# 2. Check for duplicate rows
duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows before cleaning: {duplicate_count}")

# 3. Drop duplicate rows (if any exist)
df = df.drop_duplicates()
print(f"Number of rows after dropping duplicates: {len(df)}")

# 1. Display data types before conversion
print("--- Data Types Before Conversion ---")
print(df[['Order Date', 'Ship Date']].dtypes)
print("\n" + "="*40 + "\n")

# 2. Convert Order Date and Ship Date columns to datetime format
# format='mixed' handles any slight variations in date formatting styles automatically
df['Order Date'] = pd.to_datetime(df['Order Date'], format='mixed')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='mixed')

# 3. Display data types after conversion to confirm success
print("--- Data Types After Conversion ---")
print(df[['Order Date', 'Ship Date']].dtypes)

# Export the cleaned DataFrame to a new CSV file
# index=False ensures we don't save an unnecessary row number column
output_filename = 'Superstore_Sales_Cleaned.csv'
df.to_csv(output_filename, index=False)

print(f"Success! Cleaned dataset exported as: '{output_filename}'")